### ISSUE TITLE
您好，请问我跑fddbannotation.py这个程序时，发现生成的xml文件中，会出现同一标签标两次的情况

### ISSUE THREAD

**Issue by lilmangolil** [imistyrain/fddb#3]
如上所述，例如在2002_07_19_big_img_726.xml文件中，出现了
<name>face</name>

<pose>Unspecified</pose>

<truncated>0</truncated>

<difficult>0</difficult>

-<bndbox>

<xmin>160</xmin>

<ymin>22</ymin>

<xmax>243</xmax>

<ymax>145</ymax>

</bndbox>

</object>

-<object>

<name>face</name>

<pose>Unspecified</pose>

<truncated>0</truncated>

<difficult>0</difficult>

-<bndbox>

<xmin>160</xmin>

<ymin>22</ymin>

<xmax>243</xmax>

<ymax>145</ymax>
这种情况，同一标签标了两次，而其他标签还有有的标签标两次，有的标一次的情况，请问是什么原因造成的，该如何解决呢，望您回复，感谢！

**Comment by YingXiuHe** [comment]
修改一下代码  def show_annotations() 函数中的` for k in range(len(counters))` 改为 `for k in range(1)`

**Comment by imistyrain** [comment]
for k in range(len(contours)-2)
